chart_log = {
    "symbols": ["USD/JPY"],
    "intervals": [
        "1min",
        "5min",
        "15min",
        "30min",
        "45min",
        "1h",
        "2h",
        "4h",
        "1day",
        "1week",
        "1month",
    ],
    "start_date": "2021-10-15",
    "timezone": "Asia/Tokyo",
    "bollinger_range": 20,
    "save_dir": "chart_log/",
    "TDClient_apikey": "c2e23b2dc9264f218c71475a3dd052b6",
}
data_formatter = {
    "symbol": "USD/JPY",
    "intervals": [
        "1min",
        "5min",
        "30min",
        "4h",
        "1day",
    ],
    "columns": [
        "open",
        "low",
        "high",
        "close",
        "SMA",
        "bollinger_upper",
        "bollinger_lower",
    ],
    "output_interval": "1min",
    "validation_interval": ["1min", "5min"],
    "validation_type": "upper",
    "validation_items": 2,
    "base_column": "SMA",
    "multi_thread": False,
    "threads": "auto",
    "prog_interval": 1.0,
    "margin_pips": 20,
    "middle_pips": 10000,
    "data_num": 5,
    "approximation": False,
    "label_data_range": 10000,
    "approximate_dim": 1,
    "add_candle": False,
    "save_dir": "formatted_data/",
}
