chart_log = {
    "symbols": ["USD/JPY"],
    "intervals": [
        "1min",
        "5min",
        "30min",
        "4h",
        "1day",
    ],
    "start_date": "2021-10-15",
    "timezone": "Asia/Tokyo",
    "bollinger_range": 20,
    "save_dir": "chart_log/",
    "TDClient_apikey": "c2e23b2dc9264f218c71475a3dd052b6",
}
data_formatter = {
    "symbol": "USD/JPY",
    "intervals": [
        "1min",
        "5min",
        "30min",
        "4h",
        "1day",
    ],
    "columns": [
        "open",
        "low",
        "high",
        "close",
        "SMA",
        "bollinger_upper",
        "bollinger_lower",
    ],
    "base_interval": "5min",
    "base_column": "SMA",
    "multi_thread": True,
    "threads": "auto",
    "prog_interval": 1.0,
    "margin_pips": 10,
    "middle_pips": 10000,
    "data_num": 30,
    "approximation": True,
    "label_data_range": 6,
    "approximate_dim": 4,
    "save_dir": "formatted_data/",
}
